web_server:
  bind: 0.0.0.0
  port: 50001 
#  ssl_certificate: '/etc/ssl/private/myCert.pem' 
#  ssl_private_key: '/etc/ssl/private/myKey.key' 
  web_ui: yes 
  base_url: /flex 
  run_v2: yes 


schedules:
  - tasks: [myrssfeed, task_b] 
    schedule:
      minute: "*/30" 
  - tasks: [task_c, task_d]
    schedule:
      minute: "*/30"
      hour: 22,23 
      

tasks: 
  myrssfeed: 
    rss: https://iptorrents.com/t.rss?u=1907249;tp=a3457796dfb619afff6f2260c34ff55a;60;1;86;64;35;94;26;95;98;2;47;43;45;71;50;44;69;92;58;87;77;101;89;90;96;6;48;54;62;38;68;20;100;7;3;80;93;37;36;21;55;78;23;24;25;66;82;65;83;79;22;5;99;4;85;8;81;91;84;download;free
    accept_all: yes 
      strict: no 
    download: /home/wangluoba/torrents 

    deluge:
      host：localhost 
      port: 58846 
      user: localclient 
      pass: ac39448518a7bfd9dd00eb558d2cca0579f65fcd 
      
